applications:
  app-of-apps:
    additionalAnnotations:
      "helm.sh/hook": post-install, pre-upgrade
    namespace: ${namespace}
    project: default
    source:
      repoURL: https://github.com/ricardllop/argocd-app-of-apps #replace with any app-of-apps repo
      targetRevision: main
      path: .
    destination:
      server: https://kubernetes.default.svc
      namespace: ${namespace}
    syncPolicy:
      automated:
        prune: true
        selfHeal: true